In [1]:
import matplotlib.pyplot as plt
import anndata
import scanpy as sc
import snapatac2 as snap
import numpy as np
import pandas as pd
import os
import scanpy.external as sce
import seaborn as sns
from sklearn.metrics import silhouette_score

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
adata_concat = snap.read_dataset('/data2st1/junyi/output/atac1112/doublet_filtered.h5ads/_dataset.h5ads')

In [4]:
df_meta_all = pd.read_csv('/data2st1/junyi/output/atac1112/ATACSC_3REGION_ALL_L2annoated.csv',index_col=0)

In [11]:
df_l3l4 = pd.read_csv('/data2st1/junyi/output/atac1112/iterative/annotated_l3l4.csv',index_col=0)

In [12]:
df_meta_all.head()

,sample,doublet_probability,doublet_score,leiden,leiden_default,leiden_res_0.1,leiden_res_0.2,leiden_res_0.3,leiden_res_0.4,leiden_res_0.5,...,Sample_name,Condition,Region,celltype.L2.raw,celltype.L2.refined,region_nt,celltype.L3_x,celltype.L4_x,celltype.L3_y,celltype.L4_y
MC37A_AMY:AAACGAAAGAGTGGAA-1,MC37A_AMY,0.092856,0.130307,2,6,0,0,1,1,5,...,MC37A_AMY,MC,AMY,AMY Meis1_Abi3bp Glut,AMY Meis1_Abi3bp Glut,AMY_Glut,AMY Meis1_Abi3bp Glut-1,AMY Meis1_Abi3bp Glut-1-0,AMY Meis1_Abi3bp Glut-1,AMY Meis1_Abi3bp Glut-1-0
MC37A_AMY:AAACGAAAGGGTAGTC-1,MC37A_AMY,0.128610,0.014116,18,7,4,5,5,6,7,...,MC37A_AMY,MC,AMY,Microglia-1,Perivascular Macrophage,NN,Microglia-1-1,Microglia-1-1-1,Microglia-1-1,Microglia-1-1-1
MC37A_AMY:AAACGAAGTACGGAGT-1,MC37A_AMY,0.118241,0.019370,4,1,0,0,1,1,1,...,MC37A_AMY,MC,AMY,AMY Maf_Pthlh GABA,AMY Maf_Pthlh GABA,AMY_GABA,NaN,NaN,NaN,NaN
MC37A_AMY:AAACGAAGTCAGCAAG-1,MC37A_AMY,0.074653,0.063387,6,6,0,0,1,1,5,...,MC37A_AMY,MC,AMY,AMY Zfhx4_Pde7b GABA,AMY Zfhx4_Pde7b GABA,AMY_GABA,AMY Zfhx4_Pde7b GABA-1,AMY Zfhx4_Pde7b GABA-1-1,AMY Zfhx4_Pde7b GABA-1,AMY Zfhx4_Pde7b GABA-1-1
MC37A_AMY:AAACGAAGTCCGAGCT-1,MC37A_AMY,0.098286,0.032532,1,8,0,0,1,1,1,...,MC37A_AMY,MC,AMY,AMY Meis1_Abi3bp Glut,AMY Meis1_Abi3bp Glut,AMY_Glut,AMY Meis1_Abi3bp Glut-0,AMY Meis1_Abi3bp Glut-0-0,AMY Meis1_Abi3bp Glut-0,AMY Meis1_Abi3bp Glut-0-0

In [13]:
df_l3l4.head()

,celltype.L3,celltype.L4,celltype.L4.raw
MC37A_AMY:AAAGGATAGCATTGGG-1,AMY Rai14_Foxp2 GABA-0,AMY Rai14_Foxp2 GABA-0-0,AMY Rai14_Foxp2 GABA-0-1
MC37A_AMY:ACAAACCGTCAGAGTG-1,AMY Rai14_Foxp2 GABA-0,AMY Rai14_Foxp2 GABA-0-0,AMY Rai14_Foxp2 GABA-0-1
MC37A_AMY:ACAATCGCAGAAAGAG-1,AMY Rai14_Foxp2 GABA-0,AMY Rai14_Foxp2 GABA-0-0,AMY Rai14_Foxp2 GABA-0-0
MC37A_AMY:ACAGAAAGTAGAATAC-1,AMY Rai14_Foxp2 GABA-0,AMY Rai14_Foxp2 GABA-0-0,AMY Rai14_Foxp2 GABA-0-1
MC37A_AMY:ACAGCGCAGTGAGCAC-1,AMY Rai14_Foxp2 GABA-0,AMY Rai14_Foxp2 GABA-0-0,AMY Rai14_Foxp2 GABA-0-1

In [14]:
df_meta_all = df_meta_all.merge(df_l3l4[['celltype.L3','celltype.L4']],left_index=True,right_index=True,how='left')

In [17]:
%time dmr_mat = snap.pp.make_peak_matrix(adata_concat,peak_file='/data2st1/junyi/output/atac1112/cCRE/dmr_3regions_ext.bed')

CPU times: user 1h 52min 30s, sys: 19min 18s, total: 2h 11min 49s
Wall time: 6min 39s

In [18]:
dmr_mat.write(f"/data2st1/junyi/output/atac1112/3REGIONS_dmr.h5ads")

... storing 'sample' as categorical
... storing 'celltype.L1' as categorical
... storing 'celltype.L2' as categorical
... storing 'Neurotransmitter_celltype' as categorical
... storing 'celltype.L1_ct' as categorical
... storing 'Sample_name' as categorical
... storing 'Condition' as categorical
... storing 'Region' as categorical
... storing 'celltype.L2.raw' as categorical
... storing 'region_nt' as categorical
... storing 'celltype.L3' as categorical
... storing 'celltype.L4' as categorical
... storing 'celltype.L2.refined' as categorical

In [19]:
adata_concat.close()