In [1]:
import scanpy as sc
import numpy as np

In [2]:
adata = sc.read_h5ad('/data2st1/junyi/output/atac1112/3REGIONS_peak.h5ads')

In [4]:
adata.obs['celltype.L4_sample'] = adata.obs['celltype.L4'].astype(str) + '_' + adata.obs['sample'].astype(str)

In [5]:
adata.obs

,sample,doublet_probability,doublet_score,leiden,leiden_default,leiden_res_0.1,leiden_res_0.2,leiden_res_0.3,leiden_res_0.4,leiden_res_0.5,...,Sample_name,Condition,Region,celltype.L2.raw,region_nt,celltype.L3,celltype.L4,celltype.L2.refined,expriment,celltype.L4_sample
MC37A_AMY:AAACGAAAGAGTGGAA-1,MC37A_AMY,0.092856,0.130307,2,6,0,0,1,1,5,...,MC37A_AMY,MC,AMY,AMY Meis1_Abi3bp Glut,AMY_Glut,AMY_Meis1_Abi3bp_Glut-1,AMY_Meis1_Abi3bp_Glut-1-0,AMY Meis1_Abi3bp Glut,MC,AMY_Meis1_Abi3bp_Glut-1-0_MC37A_AMY
MC37A_AMY:AAACGAAAGGGTAGTC-1,MC37A_AMY,0.128610,0.014116,18,7,4,5,5,6,7,...,MC37A_AMY,MC,AMY,Microglia-1,NN,Microglia-1-1,Microglia-1-1-1,Perivascular Macrophage,MC,Microglia-1-1-1_MC37A_AMY
MC37A_AMY:AAACGAAGTACGGAGT-1,MC37A_AMY,0.118241,0.019370,4,1,0,0,1,1,1,...,MC37A_AMY,MC,AMY,AMY Maf_Pthlh GABA,AMY_GABA,AMY_Maf_Pthlh_GABA-0,AMY_Maf_Pthlh_GABA-0-0,AMY Maf_Pthlh GABA,MC,AMY_Maf_Pthlh_GABA-0-0_MC37A_AMY
MC37A_AMY:AAACGAAGTCAGCAAG-1,MC37A_AMY,0.074653,0.063387,6,6,0,0,1,1,5,...,MC37A_AMY,MC,AMY,AMY Zfhx4_Pde7b GABA,AMY_GABA,AMY_Zfhx4_Pde7b_GABA-1,AMY_Zfhx4_Pde7b_GABA-1-1,AMY Zfhx4_Pde7b GABA,MC,AMY_Zfhx4_Pde7b_GABA-1-1_MC37A_AMY
MC37A_AMY:AAACGAAGTCCGAGCT-1,MC37A_AMY,0.098286,0.032532,1,8,0,0,1,1,1,...,MC37A_AMY,MC,AMY,AMY Meis1_Abi3bp Glut,AMY_Glut,AMY_Meis1_Abi3bp_Glut-0,AMY_Meis1_Abi3bp_Glut-0-0,AMY Meis1_Abi3bp Glut,MC,AMY_Meis1_Abi3bp_Glut-0-0_MC37A_AMY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MW65A_AMY:TTTGTGTGTTCCTGTC-1,MW65A_AMY,0.145827,0.008648,2,6,0,0,1,1,5,...,MW65A_AMY,MW,AMY,AMY Rai14_Foxp2 GABA,AMY_GABA,AMY_Rai14_Foxp2_GABA-0,AMY_Rai14_Foxp2_GABA-0-0,AMY Rai14_Foxp2 GABA,MW,AMY_Rai14_Foxp2_GABA-0-0_MW65A_AMY
MW65A_AMY:TTTGTGTTCAACGTGT-1,MW65A_AMY,0.118720,0.026467,6,6,0,0,1,1,5,...,MW65A_AMY,MW,AMY,AMY Foxp2_Penk GABA,AMY_GABA,AMY_Foxp2_Penk_GABA-0,AMY_Foxp2_Penk_GABA-0-1,AMY Foxp2_Penk GABA,MW,AMY_Foxp2_Penk_GABA-0-1_MW65A_AMY
MW65A_AMY:TTTGTGTTCATACTTC-1,MW65A_AMY,0.136702,0.013699,4,1,0,0,1,1,1,...,MW65A_AMY,MW,AMY,AMY Maf_Pthlh GABA,AMY_GABA,AMY_Maf_Pthlh_GABA-0,AMY_Maf_Pthlh_GABA-0-0,AMY Maf_Pthlh GABA,MW,AMY_Maf_Pthlh_GABA-0-0_MW65A_AMY
MW65A_AMY:TTTGTGTTCTGAGTAC-1,MW65A_AMY,0.128606,0.018868,10,10,5,6,6,7,8,...,MW65A_AMY,MW,AMY,Astrocyte-1,NN,Astrocyte-1-1,Astrocyte-1-1-1,Astrocyte-1,MW,Astrocyte-1-1-1_MW65A_AMY
MW65A_AMY:TTTGTGTTCTGCCGAG-1,MW65A_AMY,0.096046,0.063584,2,8,0,0,1,1,5,...,MW65A_AMY,MW,AMY,AMY Meis1_Abi3bp Glut,AMY_Glut,AMY_Meis1_Abi3bp_Glut-0,AMY_Meis1_Abi3bp_Glut-0-0,AMY Meis1_Abi3bp Glut,MW,AMY_Meis1_Abi3bp_Glut-0-0_MW65A_AMY

In [6]:
adata_agg = sc.get.aggregate(adata, by='celltype.L4_sample', layer='count', func=["sum", "count_nonzero"])

In [10]:
adata_agg.X = adata_agg.layers['sum']

In [29]:
adata_agg.X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.31589968, ..., 0.        , 0.        ,
        0.55559935],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 2.15597326, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [12]:
sc.pp.filter_cells(adata_agg, min_genes=100)
sc.pp.filter_genes(adata_agg, min_cells=3)

In [13]:
sc.pp.normalize_total(adata_agg)
# Logarithmize the data
sc.pp.log1p(adata_agg)

In [16]:
adata_agg.obs

,celltype.L4_sample,n_genes
AMY_Cav1_Frmpd1_Glut-0-0_MC37A_AMY,AMY_Cav1_Frmpd1_Glut-0-0_MC37A_AMY,239462
AMY_Cav1_Frmpd1_Glut-0-0_MC50B_AMY,AMY_Cav1_Frmpd1_Glut-0-0_MC50B_AMY,661757
AMY_Cav1_Frmpd1_Glut-0-0_MW47A_AMY,AMY_Cav1_Frmpd1_Glut-0-0_MW47A_AMY,834640
AMY_Cav1_Frmpd1_Glut-0-0_MW51A_AMY,AMY_Cav1_Frmpd1_Glut-0-0_MW51A_AMY,35702
AMY_Cav1_Frmpd1_Glut-0-0_MW65A_AMY,AMY_Cav1_Frmpd1_Glut-0-0_MW65A_AMY,338314
...,...,...
VLMC-0-0_MW47A_PFC,VLMC-0-0_MW47A_PFC,203497
VLMC-0-0_MW51A_AMY,VLMC-0-0_MW51A_AMY,145354
VLMC-0-0_MW51A_HIP,VLMC-0-0_MW51A_HIP,41805
VLMC-0-0_MW51A_PFC,VLMC-0-0_MW51A_PFC,119466
VLMC-0-0_MW65A_AMY,VLMC-0-0_MW65A_AMY,15112

In [17]:
adata_agg.obs['celltype.L2'] = adata_agg.obs['celltype.L4_sample'].str[:-14]

In [21]:
adata_agg.obs['sample'] = adata_agg.obs['celltype.L4_sample'].str[-9:]

In [23]:
adata_agg.obs['sample_celltype.L2'] = adata_agg.obs['sample'] + '_' + adata_agg.obs['celltype.L2']

In [25]:
adata_agg.write_h5ad('/data2st1/junyi/output/atac1112/3REGIONS_peak_celltypeL4_agg.h5ads')

In [27]:
adata_agg = adata_agg[adata_agg.obs['celltype.L2']!='Lymphocyte', :]

In [28]:
sc.tl.rank_genes_groups(adata_agg, groupby="celltype.L2", method="wilcoxon")

/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:639: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata.uns[key_added] = {}
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:429: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "names"] = self.var_names[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:431: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "scores"] = scores[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:434: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals"] = pvals[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:444: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals_adj"] = pvals_adj[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:455: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "logfoldchanges"] = np.log2(
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:429: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "names"] = self.var_names[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:431: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "scores"] = scores[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:434: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals"] = pvals[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:444: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals_adj"] = pvals_adj[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:455: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "logfoldchanges"] = np.log2(
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:429: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "names"] = self.var_names[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:431: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "scores"] = scores[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:434: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals"] = pvals[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:444: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals_adj"] = pvals_adj[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:455: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "logfoldchanges"] = np.log2(
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:429: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "names"] = self.var_names[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:431: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "scores"] = scores[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:434: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals"] = pvals[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:444: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals_adj"] = pvals_adj[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:455: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "logfoldchanges"] = np.log2(
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:429: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "names"] = self.var_names[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:431: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "scores"] = scores[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:434: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals"] = pvals[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:444: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals_adj"] = pvals_adj[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:455: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "logfoldchanges"] = np.log2(
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:429: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "names"] = self.var_names[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:431: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "scores"] = scores[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:434: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals"] = pvals[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:444: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals_adj"] = pvals_adj[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:455: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "logfoldchanges"] = np.log2(
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:429: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "names"] = self.var_names[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:431: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "scores"] = scores[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:434: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals"] = pvals[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:444: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals_adj"] = pvals_adj[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:455: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "logfoldchanges"] = np.log2(
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:429: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "names"] = self.var_names[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:431: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "scores"] = scores[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:434: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals"] = pvals[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:444: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals_adj"] = pvals_adj[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:455: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "logfoldchanges"] = np.log2(
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:429: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "names"] = self.var_names[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:431: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "scores"] = scores[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:434: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals"] = pvals[global_indices]
/home/junyichen/anaconda3/envs/snapatac2/lib/python3.10/site-packages/scanpy/tools/_rank_genes_groups.py:444: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.stats[group_name, "pvals_adj"] = pvals_adj[global_indices]

In [30]:
adata_agg.obs

,celltype.L4_sample,n_genes,celltype.L2,sample,sample_celltype.L2
AMY_Cav1_Frmpd1_Glut-0-0_MC37A_AMY,AMY_Cav1_Frmpd1_Glut-0-0_MC37A_AMY,239462,AMY_Cav1_Frmpd1_Glut,MC37A_AMY,MC37A_AMY_AMY_Cav1_Frmpd1_Glut
AMY_Cav1_Frmpd1_Glut-0-0_MC50B_AMY,AMY_Cav1_Frmpd1_Glut-0-0_MC50B_AMY,661757,AMY_Cav1_Frmpd1_Glut,MC50B_AMY,MC50B_AMY_AMY_Cav1_Frmpd1_Glut
AMY_Cav1_Frmpd1_Glut-0-0_MW47A_AMY,AMY_Cav1_Frmpd1_Glut-0-0_MW47A_AMY,834640,AMY_Cav1_Frmpd1_Glut,MW47A_AMY,MW47A_AMY_AMY_Cav1_Frmpd1_Glut
AMY_Cav1_Frmpd1_Glut-0-0_MW51A_AMY,AMY_Cav1_Frmpd1_Glut-0-0_MW51A_AMY,35702,AMY_Cav1_Frmpd1_Glut,MW51A_AMY,MW51A_AMY_AMY_Cav1_Frmpd1_Glut
AMY_Cav1_Frmpd1_Glut-0-0_MW65A_AMY,AMY_Cav1_Frmpd1_Glut-0-0_MW65A_AMY,338314,AMY_Cav1_Frmpd1_Glut,MW65A_AMY,MW65A_AMY_AMY_Cav1_Frmpd1_Glut
...,...,...,...,...,...
VLMC-0-0_MW47A_PFC,VLMC-0-0_MW47A_PFC,203497,VLMC,MW47A_PFC,MW47A_PFC_VLMC
VLMC-0-0_MW51A_AMY,VLMC-0-0_MW51A_AMY,145354,VLMC,MW51A_AMY,MW51A_AMY_VLMC
VLMC-0-0_MW51A_HIP,VLMC-0-0_MW51A_HIP,41805,VLMC,MW51A_HIP,MW51A_HIP_VLMC
VLMC-0-0_MW51A_PFC,VLMC-0-0_MW51A_PFC,119466,VLMC,MW51A_PFC,MW51A_PFC_VLMC
VLMC-0-0_MW65A_AMY,VLMC-0-0_MW65A_AMY,15112,VLMC,MW65A_AMY,MW65A_AMY_VLMC

In [44]:
for ct in adata_agg.obs['celltype.L2'].unique():
    df_cts = sc.get.rank_genes_groups_df(adata_agg, group=ct,pval_cutoff=0.05)
    df_cts.to_csv(f'/data2st1/junyi/output/atac1112/dar/cts/wilcoxon/{ct}.csv', index=False)

In [45]:
import glob
df_files = glob.glob('/data2st1/junyi/output/atac1112/dar/cts/wilcoxon/*.csv')

In [73]:
import pandas as pd
import os
import pybedtools

for file in df_files:
    df_cts = pd.read_csv(file)
    df_selected = df_cts[(df_cts['logfoldchanges']>0.1)]
    filename = os.path.basename(file).replace('.csv','.bed')
    if df_selected.shape[0]==0:
        continue
    df_bed = df_selected['names'].str.split(r'[-:]', expand=True)
    bed_object = pybedtools.BedTool.from_dataframe(df_bed)
    bed_object.sort().saveas(f'/data2st1/junyi/output/atac1112/cCRE/L2ctspeaks/{filename}')
    #sort_values(by=[0,1]).to_csv(f'/data2st1/junyi/output/atac1112/cCRE/L2ctspeaks/{filename}',sep='\t', header=False, index=False)

In [58]:
df_selected['names'].str.split(r'[-:]', expand=True).sort_values(by=[0,1])

          0          1          2
5079   chr1   10019195   10019696
8242   chr1  100430331  100430832
563    chr1  101683970  101684471
10371  chr1  102035230  102035731
5163   chr1  102678625  102679126
...     ...        ...        ...
7411   chrX   98856012   98856513
10026  chrX   98858213   98858714
13877  chrX   99592937   99593438
17846  chrX   99597159   99597660
3411   chrX    9984094    9984595

[18055 rows x 3 columns]

In [ ]:
sc.get.aggregate(adata, groupby='celltype.L1_ct', use_raw=False, layer=None, func='mean', as_dataframe=True)

In [ ]:
target = 20000
for region in ['PFC','AMY','HIP']:
    obs_region= adata.obs[adata.obs['Region']==region]
    n = obs_region.shape[0]
    if n > target:
        idx = np.random.choice(n, target, replace=False)
        idx_obs = obs_region.index[idx]
    adata_region = adata[idx_obs,:].to_memory()
    adata_region.write_h5ad(f'/data2st1/junyi/output/atac1112/subset/{region}_20k.h5ad')

In [ ]:
target = 2000
for region in ['PFC','AMY','HIP']:
    adata_region = sc.read_h5ad(f'/data2st1/junyi/output/atac1112/subset/{region}_20k.h5ad',backed='r')
    obs= adata_region.obs

    n = obs.shape[0]
    if n > target:
        idx = np.random.choice(n, target, replace=False)
        idx_obs = obs.index[idx]
    adata_region_sub = adata_region[idx_obs,:].to_memory()
    adata_region_sub.write_h5ad(f'/data2st1/junyi/output/atac1112/subset/region_nt/{region}_{region}_2k.h5ad')