In [1]:
import pandas as pd
import glob as glob
from Bio.Seq import Seq
import os

from Bio import motifs

In [2]:
files =glob.glob('/data2st1/junyi/scenic/mouse/motif/singletons/*')

In [3]:
outdir = '/data2st1/junyi/scenic/mouse/motif/merged_cluster'

In [4]:
tbffile = '/data2st1/junyi/scenic/mouse/motif/motifs-v10nr_clust-nr.mgi-m0.001-o0.0.tbl'

In [5]:
TFoutdir = '/data2st1/junyi/output/atac0627/snregulation/'

In [6]:
df_important_TF = pd.read_csv(f'/data2st1/junyi/output/atac0627/snregulation/TFregulon_analysis_important_TF_gender_new.csv')

In [9]:
df_tbffile = pd.read_csv(tbffile, sep='\t')

/tmp/ipykernel_2586587/313275177.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_tbffile = pd.read_csv(tbffile, sep='\t')

In [10]:
df = df_tbffile
motif_similarity_fdr = 0.001,
orthologous_identity_threshold  = 0.0
df.rename(columns={'#motif_id':"MotifID",
                    'gene_name':"TF",
                    'motif_similarity_qvalue': "MotifSimilarityQvalue",
                    'orthologous_identity': "OrthologousIdentity",
                    'description': "Annotation" }, inplace=True)
df = df[(df["MotifSimilarityQvalue"] <= motif_similarity_fdr) &
        (df["OrthologousIdentity"] >= orthologous_identity_threshold)]

In [11]:
df

,MotifID,motif_name,motif_description,source_name,source_version,TF,MotifSimilarityQvalue,similar_motif_id,similar_motif_description,OrthologousIdentity,orthologous_gene_name,orthologous_species,Annotation
0,metacluster_196.3,EcR_usp,EcR/usp,bergman,1.1,Hnf4a,0.000000e+00,None,None,0.265823,FBgn0003964,D. melanogaster,gene is orthologous to FBgn0003964 in D. melan...
1,metacluster_196.3,EcR_usp,EcR/usp,bergman,1.1,Hnf4g,0.000000e+00,None,None,0.279221,FBgn0003964,D. melanogaster,gene is orthologous to FBgn0003964 in D. melan...
2,metacluster_196.3,EcR_usp,EcR/usp,bergman,1.1,Nr1d1,0.000000e+00,None,None,0.156098,FBgn0000546,D. melanogaster,gene is orthologous to FBgn0000546 in D. melan...
3,metacluster_196.3,EcR_usp,EcR/usp,bergman,1.1,Nr1d2,0.000000e+00,None,None,0.170139,FBgn0000546,D. melanogaster,gene is orthologous to FBgn0000546 in D. melan...
4,metacluster_196.3,EcR_usp,EcR/usp,bergman,1.1,Nr1h2,0.000000e+00,None,None,0.327354,FBgn0000546,D. melanogaster,gene is orthologous to FBgn0000546 in D. melan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
252121,metacluster_179.4,YPL089C_419,YPL089C_419,yetfasco,1.02,Mef2a,4.378370e-06,metacluster_179.4,BORCS8-MEF2B[gene ID: ENSG00000064489 species:...,0.956436,ENSG00000068305,H. sapiens,motif similar to cisbp__M08212 ('BORCS8-MEF2B[...
252122,metacluster_145.8,YPR052C_879,YPR052C_879,yetfasco,1.02,Hoxb7,1.918920e-06,cisbp__M00332,HOXB7[gene ID: ENSG00000260027 species: Homo s...,0.940092,ENSG00000260027,H. sapiens,motif similar to cisbp__M00332 ('HOXB7[gene ID...
252123,metacluster_145.8,YPR052C_879,YPR052C_879,yetfasco,1.02,Tbp,7.388670e-08,metacluster_145.8,V$TBP_06: Tbp,1.000000,None,None,gene is annotated for similar motif transfac_p...
252124,metacluster_145.8,YPR052C_879,YPR052C_879,yetfasco,1.02,Tbpl2,4.890880e-06,jaspar__MA0386.1,SPT15,0.579167,YER148W,S. cerevisiae,motif similar to jaspar__MA0386.1 ('SPT15'; q-...
252125,yetfasco__YPR086W_1327,YPR086W_1327,YPR086W_1327,yetfasco,1.02,Gtf2b,0.000000e+00,None,None,0.357595,YPR086W,S. cerevisiae,gene is orthologous to YPR086W in S. cerevisia...

In [12]:
df_direct_annot = df[df['Annotation'] == 'gene is directly annotated']
#df_direct_annot = df_direct_annot.groupby(['MotifID'])['TF'].apply(lambda x: ', '.join(list(set(x)))).reset_index()

In [13]:
df_direct_annot

,MotifID,motif_name,motif_description,source_name,source_version,TF,MotifSimilarityQvalue,similar_motif_id,similar_motif_description,OrthologousIdentity,orthologous_gene_name,orthologous_species,Annotation
183,c2h2_zfs__M0369,M0369,ENSMUSG00000000317,c2h2_zfs,0.90,Bcl6b,0.0,None,None,1.0,None,None,gene is directly annotated
184,c2h2_zfs__M0373,M0373,ENSMUSG00000022228,c2h2_zfs,0.90,Zscan26,0.0,None,None,1.0,None,None,gene is directly annotated
185,c2h2_zfs__M0385,M0385,ENSMUSG00000028890,c2h2_zfs,0.90,Mtf1,0.0,None,None,1.0,None,None,gene is directly annotated
186,c2h2_zfs__M0393,M0393,ENSMUSG00000033863,c2h2_zfs,0.90,Klf9,0.0,None,None,1.0,None,None,gene is directly annotated
189,c2h2_zfs__M0400,M0400,ENSMUSG00000041703,c2h2_zfs,0.90,Zic5,0.0,None,None,1.0,None,None,gene is directly annotated
...,...,...,...,...,...,...,...,...,...,...,...,...,...
251819,transfac_public__M00532,M00532,V$RP58_01: RP58,transfac_public,7.0,Zbtb18,0.0,None,None,1.0,None,None,gene is directly annotated
251825,metacluster_71.11,M00538,V$HTF_01: HTF (XBP1),transfac_public,7.0,Xbp1,0.0,None,None,1.0,None,None,gene is directly annotated
251826,metacluster_57.3,M00539,V$ARNT_02: Arnt,transfac_public,7.0,Arnt,0.0,None,None,1.0,None,None,gene is directly annotated
251904,metacluster_198.2,M00615,V$MYCMAX_03: c-Myc:Max,transfac_public,7.0,Max,0.0,None,None,1.0,None,None,gene is directly annotated
251912,metacluster_198.2,M00615,V$MYCMAX_03: c-Myc:Max,transfac_public,7.0,Myc,0.0,None,None,1.0,None,None,gene is directly annotated

In [14]:
motif_similarity_annot = df[df['Annotation'].str.contains('similar') & ~df['Annotation'].str.contains('orthologous')]
#motif_similarity_annot = motif_similarity_annot.groupby(['MotifID'])['TF'].apply(lambda x: ', '.join(list(set(x)))).reset_index()

In [15]:
direct_motif_TFs = df_direct_annot[df_direct_annot.TF.isin(df_important_TF.TF)]

In [16]:
direct_motif_TFs = direct_motif_TFs.groupby(['MotifID'])['TF'].apply(lambda x: ', '.join(list(set(x)))).reset_index()

In [17]:
extended_motif_TFs = motif_similarity_annot[motif_similarity_annot.TF.isin(df_important_TF.TF)]
extended_motif_TFs = extended_motif_TFs.groupby(['MotifID'])['TF'].apply(lambda x: ', '.join(list(set(x)))).reset_index()

In [19]:
df_important_TF.TF

0       Npdc1
1       Npdc1
2        Cux1
3        Jund
4      Bclaf1
        ...
221      Zeb1
222    Zbtb16
223    Zbtb7a
224      Pbx3
225    Zbtb16
Name: TF, Length: 226, dtype: object

In [20]:
direct_motifs = []
for f in files:
    bn = os.path.basename(f).removesuffix('.cb')
    if bn not in direct_motif_TFs['MotifID'].values:
        #print(f"Skipping {bn} as it is not in the important TF list.")
        continue
    try:
        with open(f) as handle:
            m = motifs.read(handle, "ClusterBuster")
            direct_motifs.append(m)
    except ValueError:
        with open(f) as handle:
            records = motifs.parse(handle, "ClusterBuster")
            for record in records:
                record.name = bn+"#"+record.name
                direct_motifs.append(record)

In [23]:
with open(os.path.join(outdir, 'direct_im_motifs.jaspar'), 'w') as handle:
        for motif in direct_motifs:
            print(motif.format("jaspar"), file=handle)

In [26]:
extend_motifs = []
for f in files:
    bn = os.path.basename(f).removesuffix('.cb')
    if bn not in extended_motif_TFs['MotifID'].values:
        #print(f"Skipping {bn} as it is not in the important TF list.")
        continue
    try:
        with open(f) as handle:
            m = motifs.read(handle, "ClusterBuster")
            extend_motifs.append(m)
    except ValueError:
        with open(f) as handle:
            records = motifs.parse(handle, "ClusterBuster")
            for record in records:
                record.name = bn+"#"+record.name
                extend_motifs.append(record)

In [27]:
with open(os.path.join(outdir, 'extended_im_motifs.jaspar'), 'w') as handle:
        for motif in extend_motifs:
            print(motif.format("jaspar"), file=handle)

In [28]:
# merge all motifs in one indivudual jaspar file
all_motifs = []
for f in files:
    bn = os.path.basename(f).removesuffix('.cb')
    try:
        with open(f) as handle:
            m = motifs.read(handle, "ClusterBuster")
            all_motifs.append(m)
    except ValueError:
        with open(f) as handle:
            records = motifs.parse(handle, "ClusterBuster")
            for record in records:
                record.name = bn+"#"+record.name
                all_motifs.append(record)

In [ ]:
with open(os.path.join(outdir, 'merged_all_motifs.cb'), 'w') as handle:
        for motif in all_motifs:
            print(motif.format("jaspar"), file=handle)