In [14]:
import pandas as pd
import glob as glob
from Bio.Seq import Seq
import os

from Bio import motifs

In [15]:
files =glob.glob('/data2st1/junyi/scenic/mouse/motif/singletons/*')

In [16]:
outdir = '/data2st1/junyi/scenic/mouse/motif/merged_cluster'

In [17]:
tbffile = '/data2st1/junyi/scenic/mouse/motif/motifs-v10nr_clust-nr.mgi-m0.001-o0.0.tbl'

In [18]:
TFoutdir = '/data2st1/junyi/output/atac1112/snregulation/'

In [19]:
df_important_TF = pd.read_csv(f'/data2st2/junyi/output/stg1028/CUMS_4VN/scenicwil_tfs_fdr_log2fc0/significant_TFlist.csv',header=None)

In [20]:
df_important_TF.columns = ['TF']

In [21]:
df_important_TF

           TF
0       Glis2
1    Gtf2ird1
2       Tead1
3       Zmiz1
4         Tef
..        ...
287     Deaf1
288      Nfia
289     Uqcrb
290      Bdp1
291      Atf7

[292 rows x 1 columns]

In [22]:
df_tbffile = pd.read_csv(tbffile, sep='\t')

/tmp/ipykernel_1823918/313275177.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_tbffile = pd.read_csv(tbffile, sep='\t')

In [23]:
df = df_tbffile
motif_similarity_fdr = 0.001,
orthologous_identity_threshold  = 0.0
df.rename(columns={'#motif_id':"MotifID",
                    'gene_name':"TF",
                    'motif_similarity_qvalue': "MotifSimilarityQvalue",
                    'orthologous_identity': "OrthologousIdentity",
                    'description': "Annotation" }, inplace=True)
df = df[(df["MotifSimilarityQvalue"] <= motif_similarity_fdr) &
        (df["OrthologousIdentity"] >= orthologous_identity_threshold)]

In [24]:
df

,MotifID,motif_name,motif_description,source_name,source_version,TF,MotifSimilarityQvalue,similar_motif_id,similar_motif_description,OrthologousIdentity,orthologous_gene_name,orthologous_species,Annotation
0,metacluster_196.3,EcR_usp,EcR/usp,bergman,1.1,Hnf4a,0.000000e+00,None,None,0.265823,FBgn0003964,D. melanogaster,gene is orthologous to FBgn0003964 in D. melan...
1,metacluster_196.3,EcR_usp,EcR/usp,bergman,1.1,Hnf4g,0.000000e+00,None,None,0.279221,FBgn0003964,D. melanogaster,gene is orthologous to FBgn0003964 in D. melan...
2,metacluster_196.3,EcR_usp,EcR/usp,bergman,1.1,Nr1d1,0.000000e+00,None,None,0.156098,FBgn0000546,D. melanogaster,gene is orthologous to FBgn0000546 in D. melan...
3,metacluster_196.3,EcR_usp,EcR/usp,bergman,1.1,Nr1d2,0.000000e+00,None,None,0.170139,FBgn0000546,D. melanogaster,gene is orthologous to FBgn0000546 in D. melan...
4,metacluster_196.3,EcR_usp,EcR/usp,bergman,1.1,Nr1h2,0.000000e+00,None,None,0.327354,FBgn0000546,D. melanogaster,gene is orthologous to FBgn0000546 in D. melan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
252121,metacluster_179.4,YPL089C_419,YPL089C_419,yetfasco,1.02,Mef2a,4.378370e-06,metacluster_179.4,BORCS8-MEF2B[gene ID: ENSG00000064489 species:...,0.956436,ENSG00000068305,H. sapiens,motif similar to cisbp__M08212 ('BORCS8-MEF2B[...
252122,metacluster_145.8,YPR052C_879,YPR052C_879,yetfasco,1.02,Hoxb7,1.918920e-06,cisbp__M00332,HOXB7[gene ID: ENSG00000260027 species: Homo s...,0.940092,ENSG00000260027,H. sapiens,motif similar to cisbp__M00332 ('HOXB7[gene ID...
252123,metacluster_145.8,YPR052C_879,YPR052C_879,yetfasco,1.02,Tbp,7.388670e-08,metacluster_145.8,V$TBP_06: Tbp,1.000000,None,None,gene is annotated for similar motif transfac_p...
252124,metacluster_145.8,YPR052C_879,YPR052C_879,yetfasco,1.02,Tbpl2,4.890880e-06,jaspar__MA0386.1,SPT15,0.579167,YER148W,S. cerevisiae,motif similar to jaspar__MA0386.1 ('SPT15'; q-...
252125,yetfasco__YPR086W_1327,YPR086W_1327,YPR086W_1327,yetfasco,1.02,Gtf2b,0.000000e+00,None,None,0.357595,YPR086W,S. cerevisiae,gene is orthologous to YPR086W in S. cerevisia...

In [25]:
df_direct_annot = df[df['Annotation'] == 'gene is directly annotated']
#df_direct_annot = df_direct_annot.groupby(['MotifID'])['TF'].apply(lambda x: ', '.join(list(set(x)))).reset_index()

In [26]:
df_direct_annot

,MotifID,motif_name,motif_description,source_name,source_version,TF,MotifSimilarityQvalue,similar_motif_id,similar_motif_description,OrthologousIdentity,orthologous_gene_name,orthologous_species,Annotation
183,c2h2_zfs__M0369,M0369,ENSMUSG00000000317,c2h2_zfs,0.90,Bcl6b,0.0,None,None,1.0,None,None,gene is directly annotated
184,c2h2_zfs__M0373,M0373,ENSMUSG00000022228,c2h2_zfs,0.90,Zscan26,0.0,None,None,1.0,None,None,gene is directly annotated
185,c2h2_zfs__M0385,M0385,ENSMUSG00000028890,c2h2_zfs,0.90,Mtf1,0.0,None,None,1.0,None,None,gene is directly annotated
186,c2h2_zfs__M0393,M0393,ENSMUSG00000033863,c2h2_zfs,0.90,Klf9,0.0,None,None,1.0,None,None,gene is directly annotated
189,c2h2_zfs__M0400,M0400,ENSMUSG00000041703,c2h2_zfs,0.90,Zic5,0.0,None,None,1.0,None,None,gene is directly annotated
...,...,...,...,...,...,...,...,...,...,...,...,...,...
251819,transfac_public__M00532,M00532,V$RP58_01: RP58,transfac_public,7.0,Zbtb18,0.0,None,None,1.0,None,None,gene is directly annotated
251825,metacluster_71.11,M00538,V$HTF_01: HTF (XBP1),transfac_public,7.0,Xbp1,0.0,None,None,1.0,None,None,gene is directly annotated
251826,metacluster_57.3,M00539,V$ARNT_02: Arnt,transfac_public,7.0,Arnt,0.0,None,None,1.0,None,None,gene is directly annotated
251904,metacluster_198.2,M00615,V$MYCMAX_03: c-Myc:Max,transfac_public,7.0,Max,0.0,None,None,1.0,None,None,gene is directly annotated
251912,metacluster_198.2,M00615,V$MYCMAX_03: c-Myc:Max,transfac_public,7.0,Myc,0.0,None,None,1.0,None,None,gene is directly annotated

In [43]:
dict_id2tf = dict(zip(df_direct_annot['MotifID'], df_direct_annot['TF']))

In [44]:
dict_id2tf

{'c2h2_zfs__M0369': 'Bcl6b',
 'c2h2_zfs__M0373': 'Zscan26',
 'c2h2_zfs__M0385': 'Mtf1',
 'c2h2_zfs__M0393': 'Klf9',
 'c2h2_zfs__M0400': 'Zic5',
 'c2h2_zfs__M0401': 'Zfp410',
 'c2h2_zfs__M0404': 'Zfp3',
 'c2h2_zfs__M0406': 'Zfp691',
 'c2h2_zfs__M0415': 'Zfp637',
 'c2h2_zfs__M5147': 'Egr3',
 'c2h2_zfs__M5184': 'Klf12',
 'metacluster_24.2': 'Pax4',
 'metacluster_125.2': 'Tfap2c',
 'cisbp__M00115': 'Arid3a',
 'cisbp__M00116': 'Arid5a',
 'metacluster_149.4': 'Ascl2',
 'metacluster_149.1': 'Tcf3',
 'metacluster_128.2': 'Hes1',
 'cisbp__M00120': 'Myf6',
 'metacluster_13.3': 'Usf1',
 'cisbp__M00123': 'Mafk',
 'cisbp__M00124': 'Atf1',
 'metacluster_111.4': 'Atf2',
 'cisbp__M00126': 'Mafb',
 'cisbp__M00128': 'Bcl6b',
 'cisbp__M00129': 'Glis2',
 'cisbp__M00130': 'Plagl1',
 'cisbp__M00131': 'Zscan26',
 'metacluster_160.12': 'Osr2',
 'metacluster_195.2': 'Klf7',
 'metacluster_163.1': 'Klf4',
 'cisbp__M00135': 'Zbtb7b',
 'cisbp__M00136': 'Mtf1',
 'cisbp__M00137': 'Zic1',
 'metacluster_131.7': 'Egr4',
 'cisbp__M00139': 'Zfp281',
 'cisbp__M00140': 'Zfp410',
 'metacluster_18.3': 'Nfic',
 'cisbp__M00142': 'Zfp691',
 'metacluster_133.2': 'Plag1',
 'metacluster_160.11': 'Osr1',
 'cisbp__M00145': 'Zbtb14',
 'cisbp__M00146': 'Zbtb12',
 'cisbp__M00147': 'Zscan4c',
 'cisbp__M00148': 'Zfp105',
 'cisbp__M00149': 'Zfp128',
 'cisbp__M00150': 'Zic2',
 'cisbp__M00151': 'Zic3',
 'cisbp__M00152': 'Zbtb3',
 'metacluster_67.2': 'E2f3',
 'metacluster_183.3': 'Erg',
 'metacluster_191.3': 'Elk3',
 'metacluster_166.3': 'Etv2',
 'metacluster_188.2': 'Foxj3',
 'cisbp__M00161': 'Foxj1',
 'metacluster_134.2': 'Foxa1',
 'metacluster_188.5': 'Foxo1',
 'metacluster_188.6': 'Foxl1',
 'metacluster_169.2': 'Gata3',
 'cisbp__M00166': 'Gata3',
 'cisbp__M00167': 'Gata5',
 'metacluster_182.2': 'Gcm1',
 'cisbp__M00169': 'Six6',
 'metacluster_44.4': 'Nkx3-1',
 'cisbp__M00171': 'Hnf1a',
 'metacluster_118.1': 'Pdx1',
 'cisbp__M00173': 'Irf9',
 'cisbp__M00174': 'Irf3',
 'cisbp__M00175': 'Irf4',
 'metacluster_2.8': 'Irf5',
 'cisbp__M00178': 'Srf',
 'metacluster_113.4': 'Mybl2',
 'metacluster_64.1': 'Rxra',
 'cisbp__M00182': 'Hnf4a',
 'metacluster_90.4': 'Rxrg',
 'metacluster_64.2': 'Nr2f2',
 'metacluster_64.3': 'Rara',
 'metacluster_136.3': 'Rfx1',
 'cisbp__M00187': 'Rfx7',
 'metacluster_136.2': 'Rfx5',
 'cisbp__M00189': 'Sp100',
 'metacluster_19.7': 'Gmeb2',
 'cisbp__M00192': 'Smad3',
 'cisbp__M00193': 'Tcf7',
 'cisbp__M00194': 'Hbp1',
 'cisbp__M00195': 'Cic',
 'cisbp__M00196': 'Bbx',
 'metacluster_16.2': 'Sox14',
 'metacluster_189.1': 'Tcf7',
 'cisbp__M00199': 'Sox17',
 'metacluster_77.1': 'Sox30',
 'cisbp__M00202': 'Sox15',
 'metacluster_153.4': 'Sox5',
 'cisbp__M00204': 'Sox18',
 'metacluster_4.2': 'Sry',
 'cisbp__M00207': 'Tcf7l1',
 'cisbp__M00208': 'Sox21',
 'cisbp__M00209': 'Sox7',
 'metacluster_77.2': 'Sry',
 'cisbp__M00212': 'Sox13',
 'metacluster_4.3': 'Sox9',
 'cisbp__M00214': 'Sox1',
 'metacluster_158.5': 'Tbx5',
 'cisbp__M00216': 'Tbp',
 'cisbp__M00379': 'Cux1',
 'cisbp__M00381': 'Hoxb6',
 'cisbp__M00382': 'Hoxa10',
 'cisbp__M00383': 'Hoxa4',
 'cisbp__M00385': 'Nkx2-1',
 'cisbp__M00386': 'Irx2',
 'cisbp__M00388': 'Mnx1',
 'metacluster_1.9': 'Cdx4',
 'cisbp__M00390': 'Hoxc11',
 'cisbp__M00391': 'Hoxc8',
 'metacluster_112.2': 'Uncx',
 'cisbp__M00393': 'Evx2',
 'cisbp__M00394': 'Hoxd13',
 'metacluster_0.2': 'Crx',
 'cisbp__M00397': 'Rhox6',
 'cisbp__M00398': 'Vax1',
 'metacluster_68.2': 'Snai1',
 'cisbp__M00400': 'Phox2a',
 'cisbp__M00401': 'Phox2b',
 'cisbp__M00402': 'Alx3',
 'cisbp__M00403': 'Hoxa2',
 'cisbp__M00404': 'Nkx2-5',
 'cisbp__M00405': 'Lhx1',
 'cisbp__M00408': 'Hnf1b',
 'cisbp__M00409': 'Dlx4',
 'cisbp__M00410': 'Hoxb9',
 'cisbp__M00412': 'Six6',
 'cisbp__M00413': 'Barx1',
 'cisbp__M00414': 'Msx2',
 'cisbp__M00416': 'Irx4',
 'cisbp__M00417': 'Otp',
 'cisbp__M00418': 'Otx2',
 'cisbp__M00419': 'Hmbox1',
 'metacluster_44.5': 'Nkx3-1',
 'metacluster_1.10': 'Hoxc10',
 'cisbp__M00422': 'Hoxc5',
 'cisbp__M00423': 'Dlx2',
 'metacluster_112.4': 'Meox2',
 'cisbp__M00425': 'Six2',
 'metacluster_184.33': 'Rax',
 'cisbp__M00427': 'Cdx1',
 'cisbp__M00429': 'Msx3',
 'cisbp__M00430': 'Lhx4',
 'metacluster_184.3': 'Prrx1',
 'cisbp__M00432': 'Lmx1a',
 'cisbp__M00433': 'Barhl1',
 'metacluster_184.52': 'Lhx6',
 'metacluster_192.2': 'Sry',
 'cisbp__M00436': 'Hoxd8',
 'cisbp__M00438': 'Nkx2-2',
 'cisbp__M00442': 'Nkx1-1',
 'cisbp__M00443': 'Uncx',
 'cisbp__M00444': 'Hnf1a',
 'cisbp__M00446': 'Pdx1',
 'cisbp__M00447': 'Cdx2',
 'cisbp__M00448': 'Nobox',
 'cisbp__M00449': 'Dlx5',
 'metacluster_42.4': 'Lhx3',
 'cisbp__M00452': 'Isx',
 'cisbp__M00453': 'Irx3',
 'cisbp__M00454': 'Irx3',
 'cisbp__M00455': 'Irx5',
 'cisbp__M00456': 'Irx6',
 'cisbp__M00457': 'Barx2',
 'cisbp__M00458': 'Isl2',
 'cisbp__M00459': 'Vsx1',
 'cisbp__M00460': 'Barhl2',
 'cisbp__M00461': 'Six4',
 'cisbp__M00462': 'Gbx2',
 'cisbp__M00463': 'Hdx',
 'cisbp__M00464': 'Vax2',
 'cisbp__M00465': 'Lbx2',
 'cisbp__M00466': 'Nkx6-1',
 'metacluster_184.11': 'Arx',
 'cisbp__M00468': 'Pknox2',
 'cisbp__M00469': 'Gsx2',
 'cisbp__M00470': 'Hoxc9',
 'metacluster_184.12': 'Alx1',
 'cisbp__M00472': 'Alx1',
 'cisbp__M00473': 'Hoxa13',
 'cisbp__M00474': 'Hoxa11',
 'cisbp__M00475': 'Hoxa9',
 'cisbp__M00476': 'Hoxa7',
 'cisbp__M00477': 'Hoxa7',
 'cisbp__M00478': 'Hoxa5',
 'cisbp__M00479': 'Hoxb4',
 'cisbp__M00480': 'Hoxb5',
 'cisbp__M00481': 'Hoxb7',
 'cisbp__M00482': 'Lmx1b',
 'cisbp__M00483': 'Six3',
 'cisbp__M00484': 'En2',
 'cisbp__M00485': 'Hlx',
 'cisbp__M00486': 'Prrx2',
 'cisbp__M00489': 'Crx',
 'cisbp__M00491': 'Dlx1',
 'cisbp__M00492': 'Hoxd1',
 'cisbp__M00493': 'Hoxd11',
 'cisbp__M00494': 'Hoxa6',
 'cisbp__M00495': 'Emx2',
 'metacluster_28.2': 'Nkx2-2',
 'cisbp__M00497': 'Nkx2-3',
 'cisbp__M00498': 'Prop1',
 'cisbp__M00499': 'Dbx2',
 'cisbp__M00501': 'Msx1',
 'cisbp__M00502': 'Duxbl1',
 'cisbp__M00503': 'Nkx1-2',
 'cisbp__M00505': 'Hoxb13',
 'cisbp__M00506': 'Nkx3-2',
 'cisbp__M00507': 'Hmx2',
 'cisbp__M00508': 'Hoxc12',
 'cisbp__M00509': 'Hoxd10',
 'cisbp__M00510': 'Rhox11',
 'cisbp__M00511': 'Rhox11',
 'cisbp__M00512': 'Six1',
 'cisbp__M00513': 'Pbx1',
 'cisbp__M00514': 'Nkx2-4',
 'cisbp__M00517': 'Hoxb8',
 'cisbp__M00518': 'Homez',
 'cisbp__M00519': 'En1',
 'cisbp__M00520': 'Nkx2-9',
 'cisbp__M00522': 'Nkx6-3',
 'cisbp__M00523': 'Obox3',
 'cisbp__M00524': 'Hmx1',
 'metacluster_184.7': 'Gbx1',
 'cisbp__M00526': 'Tlx2',
 'cisbp__M00527': 'Obox5',
 'cisbp__M00528': 'Obox5',
 'cisbp__M00530': 'Hoxc4',
 'cisbp__M00531': 'Hoxd3',
 'cisbp__M00533': 'Cphx1',
 'cisbp__M00534': 'Lhx8',
 'cisbp__M00540': 'Pax6',
 'cisbp__M00541': 'Pax7',
 'cisbp__M00542': 'Pax4',
 'cisbp__M00543': 'Pou1f1',
 'cisbp__M00544': 'Pou2f2 ',
 'cisbp__M00547': 'Pou4f3',
 'cisbp__M00548': 'Pou2f1',
 'cisbp__M00549': 'Pou2f3',
 'cisbp__M00551': 'Pou3f1',
 'cisbp__M00552': 'Pou3f2',
 'cisbp__M00553': 'Pou3f3',
 'cisbp__M00750': 'Ahctf1',
 'cisbp__M00751': 'Hmga2',
 'metacluster_13.4': 'Mlx',
 'metacluster_19.9': 'Srebf2',
 'cisbp__M00756': 'Nhlh2',
 'cisbp__M00757': 'Xbp1',
 'cisbp__M00758': 'Atf3',
 'cisbp__M00759': 'Atf4',
 'cisbp__M00760': 'Junb',
 'metacluster_46.4': 'Cebpa',
 'cisbp__M00762': 'Dbp',
 'cisbp__M00764': 'Zscan20',
 'metacluster_170.2': 'Sp3',
 'cisbp__M00766': 'Zfp263',
 'cisbp__M00767': 'Zscan10',
 'cisbp__M00768': 'Zscan10',
 'cisbp__M00769': 'Zscan10',
 'cisbp__M00770': 'Zfp202',
 'cisbp__M00771': 'Zkscan1',
 'cisbp__M00772': 'Mzf1',
 'cisbp__M00773': 'Mzf1',
 'cisbp__M00774': 'Zfp300',
 'cisbp__M00775': 'Zbtb1',
 'cisbp__M00777': 'Klf9',
 'cisbp__M00780': 'Zic5',
 'cisbp__M00782': 'Zfp3',
 'cisbp__M00783': 'Dnajc21',
 'cisbp__M00785': 'Zkscan5',
 'cisbp__M00786': 'Zfp637',
 'cisbp__M00788': 'Zfx',
 'cisbp__M00789': 'Dmrtc2',
 'cisbp__M00790': 'Foxj2',
 'cisbp__M00791': 'Foxg1',
 'metacluster_134.3': 'Foxo3',
 'metacluster_188.3': 'Foxo1',
 'cisbp__M00796': 'Foxc2',
 'cisbp__M00798': 'Foxo6',
 'cisbp__M00800': 'Nkx2-9',
 'cisbp__M00801': 'Pou1f1',
 'cisbp__M00803': 'Pou2f1',
 'cisbp__M00804': 'Pou3f1',
 'cisbp__M00805': 'Irf2',
 'cisbp__M00806': 'Mecp2',
 'cisbp__M00808': 'Mypop',
 'cisbp__M00809': 'Prdm11',
 'cisbp__M00810': 'Rarg',
 'metacluster_121.1': 'Esr1',
 'cisbp__M00813': 'Esr1',
 'cisbp__M00814': 'Nr2e1',
 'metacluster_90.5': 'Esrrb',
 'metacluster_11.2': 'Rxra',
 'metacluster_64.16': 'Rora',
 'cisbp__M00821': 'Ar',
 'metacluster_64.4': 'Nr2f1',
 'cisbp__M00826': 'Sox10',
 'cisbp__M00827': 'Sox3',
 'cisbp__M00828': 'Sox6',
 'metacluster_153.5': 'Sox5',
 'metacluster_158.3': 'Tbx5',
 'cisbp__M00832': 'Tbx1',
 'cisbp__M00834': 'Tbx3',
 'metacluster_111.3': 'Creb1',
 'metacluster_137.2': 'Jun',
 'cisbp__M01009': 'Foxm1',
 'cisbp__M01010': 'Foxn1',
 'metacluster_181.1': 'Zic3',
 'cisbp__M01028': 'Tbr1',
 'cisbp__M01174': 'Osr1',
 'metacluster_8.2': 'Runx3',
 'cisbp__M01476': 'Elf3',
 'cisbp__M01480': 'Spic',
 'metacluster_191.5': 'Spdef',
 'metacluster_183.4': 'Ets1',
 'cisbp__M01659': 'Arid3b',
 'cisbp__M01661': 'Arid5b',
 'cisbp__M01683': 'Setbp1',
 'metacluster_145.8': 'Tbp',
 'metacluster_14.11': 'Mitf',
 'cisbp__M01717': 'Tfap4',
 'cisbp__M01718': 'Twist2',
 'cisbp__M01719': 'Arnt',
 'cisbp__M01720': 'Arnt2',
 'metacluster_19.3': 'Srebf1',
 'cisbp__M01725': 'Srebf2',
 'cisbp__M01726': 'Hes1',
 'metacluster_14.22': 'Tfeb',
 'metacluster_17.1': 'Tcf4',
 'metacluster_17.2': 'Msc',
 'metacluster_14.10': 'Usf1',
 'cisbp__M01733': 'Sohlh2',
 'cisbp__M01734': 'Hes2',
 'cisbp__M01737': 'Figla',
 'cisbp__M01738': 'Bhlhe40',
 'cisbp__M01739': 'Bhlhe41',
 'cisbp__M01741': 'Mitf',
 'cisbp__M01742': 'Myf6',
 'cisbp__M01743': 'Mlxip',
 'cisbp__M01744': 'Tcfl5',
 'cisbp__M01745': 'Olig3',
 'metacluster_193.2': 'Tcf3',
 'cisbp__M01748': 'Neurog1',
 'cisbp__M01749': 'Bhlha15',
 'cisbp__M01751': 'Arntl',
 'cisbp__M01752': 'Usf2',
 'cisbp__M01802': 'Xbp1',
 'cisbp__M01803': 'Tef',
 'cisbp__M01804': 'Atf1',
 'cisbp__M01807': 'Atf3',
 'cisbp__M01809': 'Fosl2',
 'cisbp__M01811': 'Cebpa',
 'metacluster_139.3': 'Creb3l2',
 'cisbp__M01813': 'Crebzf',
 'cisbp__M01814': 'Mafg',
 'cisbp__M01815': 'Cebpe',
 'cisbp__M01816': 'Jun',
 'cisbp__M01817': 'Cebpg',
 'cisbp__M01819': 'Nfil3',
 'metacluster_156.3': 'Hlf',
 'cisbp__M01821': 'Crem',
 'cisbp__M01863': 'Zfp711',
 'cisbp__M01864': 'Egr1',
 'cisbp__M01980': 'Foxj2',
 'cisbp__M01981': 'Foxj3',
 'cisbp__M01982': 'Foxc1',
 'metacluster_127.1': 'Foxa2',
 'metacluster_127.2': 'Foxd1',
 'cisbp__M02098': 'Nanog',
 'metacluster_184.9': 'Duxbl1',
 'cisbp__M02100': 'Rhox11',
 'cisbp__M02101': 'Noto',
 'cisbp__M02255': 'Irf7',
 'cisbp__M02323': 'Terf2',
 'cisbp__M02386': 'Myrf',
 'cisbp__M02464': 'Sp110',
 'cisbp__M02487': 'Hmg20b',
 'cisbp__M02651': 'Arid3a',
 'cisbp__M02655': 'Arnt',
 'cisbp__M02667': 'Mecom',
 'cisbp__M02686': 'Nkx2-5',
 'cisbp__M02687': 'Lhx3',
 'cisbp__M02688': 'Nobox',
 'cisbp__M02690': 'Pax2',
 'cisbp__M02708': 'Nr2e3',
 'cisbp__M02718': 'Sox17',
 'cisbp__M02719': 'Sox5',
 'cisbp__M02722': 'Spz1',
 'cisbp__M02768': 'Tfap2a',
 'cisbp__M02769': 'Tfap2a',
 'cisbp__M02770': 'Tfap2a',
 'cisbp__M02814': 'Ascl2',
 'cisbp__M02815': 'Mlx',
 'cisbp__M02816': 'Srebf1',
 'cisbp__M02817': 'Bhlhe40',
 'metacluster_14.17': 'Bhlhe40',
 'cisbp__M02819': 'Tcf21',
 'cisbp__M02820': 'Atoh1',
 'cisbp__M02860': 'Hlf',
 'cisbp__M02861': 'Jdp2',
 'cisbp__M02862': 'Jdp2',
 'cisbp__M02863': 'Creb3l2',
 'cisbp__M02864': 'Creb3l2',
 'cisbp__M02865': 'Atf4',
 'cisbp__M02866': 'Creb5',
 'cisbp__M02867': 'Cebpb',
 'cisbp__M02868': 'Dbp',
 'cisbp__M02869': 'Mafb',
 'cisbp__M02870': 'Mafb',
 'cisbp__M02871': 'Mafb',
 'cisbp__M02931': 'Egr3',
 'cisbp__M02932': 'Egr1',
 'cisbp__M02933': 'Hic1',
 'cisbp__M02934': 'Hic1',
 'cisbp__M02935': 'Zfp740',
 'cisbp__M02936': 'Zic3',
 'cisbp__M02937': 'Klf12',
 'cisbp__M02938': 'Zfp652',
 'cisbp__M03009': 'Spic',
 'cisbp__M03010': 'Elk3',
 'cisbp__M03011': 'Elf5',
 'cisbp__M03052': 'Foxg1',
 'cisbp__M03053': 'Foxg1',
 'cisbp__M03054': 'Foxg1',
 'cisbp__M03055': 'Foxj3',
 'cisbp__M03056': 'Foxj3',
 'cisbp__M03057': 'Foxj3',
 'cisbp__M03058': 'Foxj3',
 'cisbp__M03059': 'Foxc1',
 'cisbp__M03060': 'Foxc1',
 'cisbp__M03061': 'Foxk1',
 'cisbp__M03062': 'Foxk1',
 'cisbp__M03247': 'Hoxd13',
 'cisbp__M03248': 'Hoxd13',
 'cisbp__M03249': 'Otx1',
 'cisbp__M03250': 'Otx1',
 'cisbp__M03251': 'Hoxa2',
 'cisbp__M03252': 'Hoxc10',
 'cisbp__M03253': 'Hoxc10',
 'cisbp__M03254': 'Dlx2',
 'cisbp__M03255': 'Msx3',
 'cisbp__M03256': 'Msx3',
 'cisbp__M03257': 'Lhx4',
 'cisbp__M03258': 'Barhl1',
 'cisbp__M03259': 'Barhl1',
 'cisbp__M03260': 'Barhl1',
 'cisbp__M03261': 'Meis2',
 'cisbp__M03262': 'Meis2',
 'cisbp__M03263': 'Shox2',
 'cisbp__M03264': 'Uncx',
 'cisbp__M03265': 'Uncx',
 'cisbp__M03266': 'Irx3',
 'cisbp__M03267': 'Vsx1',
 'cisbp__M03268': 'Gbx2',
 'cisbp__M03269': 'Arx',
 'cisbp__M03270': 'Pknox2',
 'cisbp__M03271': 'Meox2',
 'cisbp__M03272': 'Alx1',
 'cisbp__M03273': 'Alx1',
 'cisbp__M03274': 'Hoxa11',
 'cisbp__M03275': 'Hoxa11',
 'cisbp__M03276': 'En2',
 'cisbp__M03277': 'Prrx2',
 'cisbp__M03278': 'Alx4',
 'cisbp__M03279': 'Meis3',
 'cisbp__M03280': 'Meis3',
 'cisbp__M03281': 'Dlx1',
 'cisbp__M03282': 'Hoxd9',
 'cisbp__M03283': 'Hoxd9',
 'cisbp__M03284': 'Hoxd9',
 'cisbp__M03285': 'Rhox11',
 'cisbp__M03286': 'Gbx1',
 'cisbp__M03287': 'Hoxd3',
 'cisbp__M03288': 'Lhx8',
 'cisbp__M03289': 'Lhx8',
 'cisbp__M03290': 'Lhx8',
 'cisbp__M03322': 'Pou2f2 ',
 'cisbp__M03323': 'Pou2f2 ',
 'cisbp__M03416': 'Rarg',
 'cisbp__M03417': 'Rarg',
 'cisbp__M03418': 'Rarg',
 'cisbp__M03419': 'Nr2f6',
 'cisbp__M03420': 'Nr2f6',
 'cisbp__M03421': 'Rxra',
 'cisbp__M03422': 'Rxra',
 'cisbp__M03423': 'Rarb',
 'cisbp__M03424': 'Rarb',
 'cisbp__M03425': 'Rarb',
 'cisbp__M03426': 'Hnf4a',
 'cisbp__M03427': 'Nr2e1',
 'cisbp__M03428': 'Nr2e1',
 'cisbp__M03429': 'Vdr',
 'cisbp__M03430': 'Esrra',
 'cisbp__M03431': 'Esrra',
 'cisbp__M03432': 'Rara',
 'cisbp__M03433': 'Rara',
 'cisbp__M03434': 'Rara',
 'cisbp__M03435': 'Rxrb',
 'cisbp__M03436': 'Ar',
 'cisbp__M03438': 'Trp73',
 'cisbp__M03439': 'Trp53',
 'cisbp__M03440': 'Trp53',
 'cisbp__M03441': 'Trp53',
 'cisbp__M03461': 'Rfx2',
 'cisbp__M03462': 'Rfx2',
 'cisbp__M03463': 'Rfx3',
 'cisbp__M03532': 'Tcf7',
 'cisbp__M03533': 'Sox17',
 'cisbp__M03534': 'Sox17',
 'cisbp__M03535': 'Sox10',
 'cisbp__M03536': 'Sox10',
 'cisbp__M03537': 'Sox10',
 'cisbp__M03538': 'Sox3',
 'cisbp__M03539': 'Sox3',
 'cisbp__M03540': 'Sox3',
 'cisbp__M03541': 'Sox11',
 'cisbp__M03542': 'Sox1',
 'cisbp__M03543': 'Sox1',
 'cisbp__M03544': 'Sox1',
 'cisbp__M03545': 'Sox1',
 'metacluster_57.2': 'Usf2',
 'cisbp__M05844': 'Zeb1',
 'cisbp__M05867': 'Gata3',
 'metacluster_162.5': 'Rora',
 'metacluster_84.1': 'Rarg',
 'metacluster_185.1': 'Ar',
 'cisbp__M05889': 'Smad4',
 'metacluster_159.3': 'Ctcf',
 'cisbp__M08024': 'Bcl6',
 'metacluster_167.5': 'Spi1',
 'metacluster_175.2': 'Tfcp2l1',
 'cisbp__M08030': 'Tfcp2l1',
 'metacluster_142.2': 'Nanog',
 'metacluster_5.1': 'Rela',
 'metacluster_153.2': 'Sry',
 'metacluster_4.4': 'Sox4',
 'metacluster_29.2': 'Stat6',
 'metacluster_34.4': 'Thap11',
 'cisbp__M08060': 'Myod1',
 'cisbp__M08061': 'Myog',
 'cisbp__M08062': 'Tcf12',
 'cisbp__M08077': 'Nfe2l2',
 'cisbp__M08097': 'Bcl6',
 'cisbp__M08098': 'Gfi1b',
 'cisbp__M08099': 'Klf1',
 'cisbp__M08100': 'Zfx',
 'metacluster_191.2': 'Gabpa',
 'cisbp__M08122': 'Foxo1',
 'cisbp__M08126': 'Gata4',
 'cisbp__M08127': 'Gata1',
 'cisbp__M08136': 'Nkx2-5',
 'cisbp__M08137': 'Hoxc9',
 'cisbp__M08138': 'Hoxa9',
 'cisbp__M08139': 'Crx',
 'cisbp__M08158': 'Nr5a2',
 'cisbp__M08162': 'Rfx1',
 'cisbp__M08163': 'Runx1',
 'cisbp__M08168': 'Sox3',
 'cisbp__M08169': 'Sox6',
 'cisbp__M08170': 'Sox2',
 'cisbp__M08173': 'Stat6',
 'cisbp__M08174': 'Stat4',
 'cisbp__M08704': 'Tfap2a',
 'cisbp__M08705': 'Tfap2b',
 'cisbp__M08706': 'Tfap2c',
 'cisbp__M08708': 'Arid5b',
 'cisbp__M08743': 'Tfe3',
 'cisbp__M08744': 'Ascl2',
 'cisbp__M08745': 'Myod1',
 'cisbp__M08746': 'Arnt',
 'cisbp__M08747': 'Ahr',
 'cisbp__M08748': 'Ascl1',
 'cisbp__M08749': 'Srebf1',
 'cisbp__M08750': 'Hif1a',
 'cisbp__M08751': 'Myc',
 'cisbp__M08752': 'Srebf2',
 'cisbp__M08753': 'Tfeb',
 'cisbp__M08754': 'Mxi1',
 'cisbp__M08755': 'Myog',
 'cisbp__M08756': 'Usf1',
 'cisbp__M08757': 'Ptf1a',
 'cisbp__M08758': 'Neurog2',
 'cisbp__M08759': 'Tal1',
 'cisbp__M08760': 'Clock',
 'cisbp__M08761': 'Bhlhe40',
 'cisbp__M08762': 'Tcf12',
 'cisbp__M08763': 'Lyl1',
 'cisbp__M08764': 'Neurod1',
 'cisbp__M08765': 'Mitf',
 'cisbp__M08766': 'Twist1',
 'cisbp__M08767': 'Myf6',
 'cisbp__M08768': 'Mycn',
 'cisbp__M08769': 'Hand1',
 'cisbp__M08770': 'Neurod2',
 'cisbp__M08771': 'Olig2',
 'cisbp__M08772': 'Msgn1',
 'cisbp__M08773': 'Nhlh1',
 'cisbp__M08774': 'Bhlha15',
 'cisbp__M08775': 'Tcf4',
 'cisbp__M08776': 'Arntl',
 'cisbp__M08777': 'Usf2',
 'cisbp__M08778': 'Max',
 'cisbp__M08779': 'Atoh1',
 'cisbp__M08814': 'Fosb',
 'cisbp__M08815': 'Hlf',
 'cisbp__M08816': 'Nfe2l2',
 'cisbp__M08817': 'Mafk',
 'cisbp__M08818': 'Xbp1',
 'cisbp__M08819': 'Fos',
 'cisbp__M08820': 'Atf1',
 'cisbp__M08821': 'Fosl1',
 'cisbp__M08822': 'Ddit3',
 'cisbp__M08823': 'Bach1',
 'cisbp__M08824': 'Creb1',
 'cisbp__M08825': 'Atf3',
 'cisbp__M08826': 'Batf3',
 'cisbp__M08827': 'Atf2',
 'cisbp__M08828': 'Fosl2',
 'cisbp__M08829': 'Batf',
 'cisbp__M08830': 'Cebpa',
 'cisbp__M08831': 'Nfe2l1',
 'cisbp__M08832': 'Bach2',
 'cisbp__M08833': 'Atf4',
 'cisbp__M08834': 'Maff',
 'cisbp__M08835': 'Mafg',
 'cisbp__M08836': 'Cebpe',
 'cisbp__M08837': 'Jun',
 'cisbp__M08838': 'Junb',
 'cisbp__M08839': 'Maf',
 'cisbp__M08840': 'Cebpg',
 'cisbp__M08841': 'Cebpb',
 'cisbp__M08842': 'Nfil3',
 'cisbp__M08843': 'Nfe2',
 'cisbp__M08844': 'Dbp',
 'cisbp__M08845': 'Crem',
 'cisbp__M08846': 'Jund',
 'cisbp__M08847': 'Mafb',
 'cisbp__M08849': 'Zeb1',
 'cisbp__M08962': 'Klf6',
 'cisbp__M08963': 'Sp1',
 'cisbp__M08964': 'Klf4',
 'cisbp__M08965': 'Klf5',
 'cisbp__M08966': 'Ctcf',
 'cisbp__M08967': 'Zbtb17',
 'cisbp__M08968': 'Wt1',
 'cisbp__M08969': 'Ikzf1',
 'cisbp__M08970': 'Sp2',
 'cisbp__M08971': 'Yy1',
 'cisbp__M08972': 'Bcl6',
 'cisbp__M08973': 'Snai2',
 'cisbp__M08974': 'Ovol1',
 'cisbp__M08975': 'Sp4',
 'cisbp__M08976': 'Gli1',
 'cisbp__M08977': 'Gfi1b',
 'cisbp__M08978': 'Sp3',
 'cisbp__M08979': 'Sall4',
 'cisbp__M08980': 'Mecom',
 'cisbp__M08981': 'Mtf1',
 'cisbp__M08982': 'Klf3',
 'cisbp__M08983': 'Rest',
 'cisbp__M08984': 'Gfi1',
 'cisbp__M08985': 'Zkscan1',
 'cisbp__M08986': 'Prdm5',
 'cisbp__M08987': 'Klf15',
 'cisbp__M08988': 'Maz',
 'cisbp__M08989': 'Hinfp',
 'cisbp__M08990': 'Zic1',
 'cisbp__M08991': 'Zbtb7a',
 'cisbp__M08992': 'Zfp57',
 'cisbp__M08993': 'Ovol2',
 'cisbp__M08994': 'Egr2',
 'cisbp__M08995': 'Prdm1',
 'cisbp__M08996': 'Egr1',
 'cisbp__M08997': 'Prdm16',
 'cisbp__M08998': 'Zfp335',
 'cisbp__M08999': 'Zfp281',
 'cisbp__M09000': 'Klf8',
 'cisbp__M09001': 'Prdm14',
 'cisbp__M09002': 'Snai1',
 'cisbp__M09003': 'Hic1',
 'cisbp__M09004': 'Zfp322a',
 'cisbp__M09005': 'Zbtb33',
 'cisbp__M09006': 'Zfp42',
 'cisbp__M09007': 'Prdm9',
 'cisbp__M09008': 'Klf1',
 'cisbp__M09009': 'Sp7',
 'cisbp__M09010': 'Zfp143',
 'cisbp__M09011': 'Zic2',
 'cisbp__M09012': 'Zfp932',
 'cisbp__M09013': 'Zic3',
 'cisbp__M09014': 'Insm1',
 'cisbp__M09015': 'Ctcfl',
 'cisbp__M09016': 'Sp5',
 'cisbp__M09017': 'Zfx',
 'cisbp__M09019': 'Nfya',
 'cisbp__M09021': 'Rbpj',
 'cisbp__M09024': 'Cux1',
 'cisbp__M09025': 'Cux2',
 'cisbp__M09026': 'Onecut1',
 'cisbp__M09027': 'Dmrt1',
 'cisbp__M09028': 'Dmrtb1',
 'cisbp__M09037': 'E2f4',
 'cisbp__M09038': 'E2f3',
 'cisbp__M09039': 'E2f2',
 'cisbp__M09040': 'E2f7',
 'cisbp__M09041': 'E2f1',
 'cisbp__M09042': 'E2f5',
 'cisbp__M09043': 'E2f6',
 'cisbp__M09045': 'Ebf1',
 'cisbp__M09065': 'Spi1',
 'cisbp__M09066': 'Elf3',
 'cisbp__M09067': 'Etv2',
 'cisbp__M09068': 'Spib',
 'cisbp__M09069': 'Gabpa',
 'cisbp__M09070': 'Elk1',
 'cisbp__M09071': 'Ehf',
 'cisbp__M09072': 'Fli1',
 'cisbp__M09073': 'Etv4',
 'cisbp__M09074': 'Ets2',
 'cisbp__M09075': 'Elk4',
 'cisbp__M09076': 'Elf5',
 'cisbp__M09077': 'Etv6',
 'cisbp__M09078': 'Ets1',
 'cisbp__M09079': 'Elf1',
 'metacluster_35.2': 'Elk1',
 'cisbp__M09081': 'Erg',
 'cisbp__M09082': 'Fev',
 'cisbp__M09099': 'Foxm1',
 'cisbp__M09100': 'Foxj2',
 'cisbp__M09101': 'Foxp2',

In [27]:
motif_similarity_annot = df[df['Annotation'].str.contains('similar') & ~df['Annotation'].str.contains('orthologous')]
#motif_similarity_annot = motif_similarity_annot.groupby(['MotifID'])['TF'].apply(lambda x: ', '.join(list(set(x)))).reset_index()

In [28]:
direct_motif_TFs = df_direct_annot[df_direct_annot.TF.isin(df_important_TF.TF)]

In [29]:
direct_motif_TFs = direct_motif_TFs.groupby(['MotifID'])['TF'].apply(lambda x: ', '.join(list(set(x)))).reset_index()

In [30]:
extended_motif_TFs = motif_similarity_annot[motif_similarity_annot.TF.isin(df_important_TF.TF)]
extended_motif_TFs = extended_motif_TFs.groupby(['MotifID'])['TF'].apply(lambda x: ', '.join(list(set(x)))).reset_index()

In [31]:
df_important_TF.TF

0         Glis2
1      Gtf2ird1
2         Tead1
3         Zmiz1
4           Tef
         ...
287       Deaf1
288        Nfia
289       Uqcrb
290        Bdp1
291        Atf7
Name: TF, Length: 292, dtype: object

In [45]:
m

In [32]:
direct_motifs = []
for f in files:
    bn = os.path.basename(f).removesuffix('.cb')
    if bn not in direct_motif_TFs['MotifID'].values:
        #print(f"Skipping {bn} as it is not in the important TF list.")
        continue
    try:
        with open(f) as handle:
            m = motifs.read(handle, "ClusterBuster")
            direct_motifs.append(m)
    except ValueError:
        with open(f) as handle:
            records = motifs.parse(handle, "ClusterBuster")
            for record in records:
                record.name = bn+"#"+record.name
                direct_motifs.append(record)

In [33]:
with open(os.path.join(outdir, 'direct_im_motifs.jaspar'), 'w') as handle:
        for motif in direct_motifs:
            print(motif.format("jaspar"), file=handle)

In [34]:
extend_motifs = []
for f in files:
    bn = os.path.basename(f).removesuffix('.cb')
    if bn not in extended_motif_TFs['MotifID'].values:
        #print(f"Skipping {bn} as it is not in the important TF list.")
        continue
    try:
        with open(f) as handle:
            m = motifs.read(handle, "ClusterBuster")
            extend_motifs.append(m)
    except ValueError:
        with open(f) as handle:
            records = motifs.parse(handle, "ClusterBuster")
            for record in records:
                record.name = bn+"#"+record.name
                extend_motifs.append(record)

In [35]:
with open(os.path.join(outdir, 'extended_im_motifs.jaspar'), 'w') as handle:
        for motif in extend_motifs:
            print(motif.format("jaspar"), file=handle)

In [42]:
record.name

'metacluster_90.6#cisbp__M03402'

In [36]:
# merge all motifs in one indivudual jaspar file
all_motifs = []
for f in files:
    bn = os.path.basename(f).removesuffix('.cb')
    try:
        with open(f) as handle:
            m = motifs.read(handle, "ClusterBuster")
            all_motifs.append(m)
    except ValueError:
        with open(f) as handle:
            records = motifs.parse(handle, "ClusterBuster")
            for record in records:
                record.name = bn+"#"+record.name
                all_motifs.append(record)

In [37]:
with open(os.path.join(outdir, 'merged_all_motifs.cb'), 'w') as handle:
        for motif in all_motifs:
            print(motif.format("jaspar"), file=handle)

In [38]:
outdir

'/data2st1/junyi/scenic/mouse/motif/merged_cluster'