In [1]:
import os
import numpy as np
import pandas as pd
import scanpy as sc
import anndata as ad
import muon as mu
from muon import atac as ac
from pyjaspar import jaspardb
import pychromvar as pc

In [9]:
loc_mm10 = '/data2st1/junyi/ref/GRCm38.p6.genome.fa'

In [2]:
adata=sc.read_h5ad('/data1st2/junyi/output/atac1112/subset/region_nt/PFC_PFC_GABA.h5ad')

In [3]:
adata.obs

,sample,doublet_probability,doublet_score,leiden,leiden_default,leiden_res_0.1,leiden_res_0.2,leiden_res_0.3,leiden_res_0.4,leiden_res_0.5,...,celltype.L1_ct,Sample_name,Condition,Region,celltype.L2.raw,region_nt,celltype.L3,celltype.L4,celltype.L2.refined,expriment
MC50B_PFC:AAACTGCCACGGTTAT-1,MC50B_PFC,0.121567,0.035714,4,1,0,0,1,1,1,...,GABA,MC50B_PFC,MC,PFC,PFC Pvalb GABA,PFC_GABA,PFC_Pvalb_GABA-1,PFC_Pvalb_GABA-1-0,PFC Pvalb GABA,MC
MC50B_PFC:AAACTGCGTCGATTAC-1,MC50B_PFC,0.138635,0.024831,4,1,0,0,1,1,1,...,GABA,MC50B_PFC,MC,PFC,PFC Pvalb GABA,PFC_GABA,PFC_Pvalb_GABA-0,PFC_Pvalb_GABA-0-0,PFC Pvalb GABA,MC
MC50B_PFC:AAAGGATGTGTCGGTC-1,MC50B_PFC,0.141703,0.023256,4,1,0,0,1,1,1,...,GABA,MC50B_PFC,MC,PFC,PFC Sncg GABA,PFC_GABA,PFC_Sncg_GABA-0,PFC_Sncg_GABA-0-0,PFC Sncg GABA,MC
MC50B_PFC:AAAGGATTCCTCCATG-1,MC50B_PFC,0.138635,0.024831,4,1,0,0,1,1,1,...,GABA,MC50B_PFC,MC,PFC,PFC Pvalb GABA,PFC_GABA,PFC_Pvalb_GABA-0,PFC_Pvalb_GABA-0-0,PFC Pvalb GABA,MC
MC50B_PFC:AAAGGGCAGATGCGAC-1,MC50B_PFC,0.157649,0.016194,4,1,0,0,1,1,1,...,GABA,MC50B_PFC,MC,PFC,PFC Sst GABA,PFC_GABA,PFC_Sst_GABA-1,PFC_Sst_GABA-1-0,PFC Sst GABA,MC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MW26A_PFC:TTTGTGTAGGTTGTGG-1,MW26A_PFC,0.388409,0.010309,4,1,0,0,1,1,1,...,GABA,MW26A_PFC,MW,PFC,PFC Vip GABA,PFC_GABA,PFC_Vip_GABA-1,PFC_Vip_GABA-1-0,PFC Vip GABA,MW
MW26A_PFC:TTTGTGTGTCCTTATT-1,MW26A_PFC,0.354129,0.014599,4,1,0,0,1,1,1,...,GABA,MW26A_PFC,MW,PFC,PFC Sst GABA,PFC_GABA,PFC_Sst_GABA-0,PFC_Sst_GABA-0-0,PFC Sst GABA,MW
MW26A_PFC:TTTGTGTGTGAAACAT-1,MW26A_PFC,0.283147,0.026094,4,1,0,0,1,1,1,...,GABA,MW26A_PFC,MW,PFC,PFC Vip GABA,PFC_GABA,PFC_Vip_GABA-1,PFC_Vip_GABA-1-0,PFC Vip GABA,MW
MW26A_PFC:TTTGTGTGTGATGTGG-1,MW26A_PFC,0.404006,0.008521,4,1,0,0,1,1,1,...,GABA,MW26A_PFC,MW,PFC,PFC Sst GABA,PFC_GABA,PFC_Sst_GABA-0,PFC_Sst_GABA-0-0,PFC Sst GABA,MW
MW26A_PFC:TTTGTGTGTTGGTAAA-1,MW26A_PFC,0.326569,0.018525,4,1,0,0,1,1,1,...,GABA,MW26A_PFC,MW,PFC,PFC Vip GABA,PFC_GABA,PFC_Vip_GABA-1,PFC_Vip_GABA-1-0,PFC Vip GABA,MW

In [18]:
adata.var['chr'] = adata.var.index

In [19]:
adata.var.index = adata.var['chr'].str.replace(':', '-')

In [43]:
adata.X = adata.layers['count'] # use norm matrix for chromvar

In [44]:
sc.pp.calculate_qc_metrics(adata, percent_top=None, log1p=False, inplace=True)

In [49]:
mu.pp.filter_var(adata, 'n_cells_by_counts', lambda x: x >= 50)
mu.pp.filter_obs(adata, 'n_genes_by_counts', lambda x: (x >= 2000) )
mu.pp.filter_obs(adata, 'total_counts', lambda x: (x >= 4000))

In [50]:
adata

AnnData object with n_obs × n_vars = 6326 × 642438
    obs: 'sample', 'doublet_probability', 'doublet_score', 'leiden', 'leiden_default', 'leiden_res_0.1', 'leiden_res_0.2', 'leiden_res_0.3', 'leiden_res_0.4', 'leiden_res_0.5', 'leiden_res_0.6', 'leiden_res_0.7', 'leiden_res_0.8', 'leiden_res_0.9', 'leiden_res_1.0', 'leiden_res_1.1', 'leiden_res_1.2', 'leiden_res_1.3', 'leiden_res_1.4', 'leiden_res_1.5', 'leiden_res_1.6', 'leiden_res_1.7', 'leiden_res_1.8', 'leiden_res_1.9', 'celltype.L2.Condition', 'celltype.L1', 'celltype.L2', 'Neurotransmitter_celltype', 'celltype.L1_ct', 'Sample_name', 'Condition', 'Region', 'celltype.L2.raw', 'region_nt', 'celltype.L3', 'celltype.L4', 'celltype.L2.refined', 'expriment', 'n_genes_by_counts', 'total_counts'
    var: 'chr', 'gc_bias', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts'
    uns: 'log1p', 'peak_seq'
    obsm: 'X_spectral', 'X_umap'
    layers: 'count'

In [52]:
pc.add_peak_seq(adata, genome_file=loc_mm10)

100%|██████████| 642438/642438 [00:02<00:00, 215873.24it/s]

In [53]:
pc.add_gc_bias(adata)

100%|██████████| 642438/642438 [00:03<00:00, 190363.66it/s]
/home/junyichen/anaconda3/envs/scenicplus/lib/python3.11/site-packages/pychromvar/preprocessing.py:134: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  adata.var['gc_bias'] = bias

In [34]:
jdb_obj = jaspardb(release='JASPAR2026')
motifs = jdb_obj.fetch_motifs(
    collection = 'CORE',
    tax_group = ['vertebrates'])

In [54]:
pc.get_bg_peaks(adata)

/home/junyichen/anaconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/sparse/_index.py:145: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)

In [59]:
adata.X = adata.X.astype(np.float32)

In [61]:
pc.match_motif(adata, motifs=motifs)

100%|██████████| 642438/642438 [07:28<00:00, 1433.61it/s]

In [71]:
len(adata.uns['motif_name'])

1019

In [75]:
adata.varm['motif_match'].shape

(642438, 1019)

In [76]:
df_motif_match = pd.DataFrame(adata.varm['motif_match'], index=adata.var_names, columns=adata.uns['motif_name'])

In [78]:
dev = pc.compute_deviations(adata)

2026-06-08 15:15:29 INFO     computing expectation reads per cell and peak...
2026-06-08 15:20:10 INFO     computing observed motif deviations...
2026-06-08 15:20:38 INFO     computing background deviations...
/home/junyichen/anaconda3/envs/scenicplus/lib/python3.11/site-packages/anndata/_core/anndata.py:522: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(

In [85]:
dev.var

Empty DataFrame
Columns: []
Index: [MA0004.1.Arnt, MA0069.1.PAX6, MA0071.1.RORA, MA0074.1.RXRA::VDR, MA0101.1.REL, MA0107.1.RELA, MA0111.1.Spz1, MA0115.1.NR1H2::RXRA, MA0119.1.NFIC::TLX1, MA0130.1.ZNF354C, MA0142.1.Pou5f1::Sox2, MA0149.1.EWSR1-FLI1, MA0151.1.Arid3a, MA0155.1.INSM1, MA0159.1.RARA::RXRA, MA0163.1.PLAG1, MA0145.2.Tfcp2l1, MA0468.1.DUX4, MA0515.1.Sox6, MA0258.2.ESR2, MA0595.1.SREBF1, MA0596.1.SREBF2, MA0599.1.KLF5, MA0604.1.Atf1, MA0608.1.Creb3l2, MA0613.1.FOXG1, MA0614.1.Foxj2, MA0636.1.BHLHE41, MA0641.1.ELF4, MA0042.2.FOXI1, MA0033.2.FOXL1, MA0153.2.HNF1B, MA0486.2.HSF1, MA0653.1.IRF9, MA0655.1.JDP2, MA0660.1.MEF2B, MA0663.1.MLX, MA0665.1.MSC, MA0667.1.MYF6, MA0669.1.NEUROG2, MA0676.1.Nr2e1, MA0678.1.OLIG2, MA0068.2.PAX4, MA0512.2.Rxra, MA0083.3.SRF, MA0009.2.TBXT, MA0689.1.TBX20, MA0691.1.TFAP4, MA0696.1.ZIC1, MA0713.1.PHOX2A, MA0715.1.PROP1, MA0724.1.VENTX, MA0728.1.Nr2F6, MA0729.1.RARA, MA0730.1.RARA, MA0731.1.BCL6B, MA0472.2.EGR2, MA0736.1.GLIS2, MA0737.1.GLIS3, MA0741.1.KLF16, MA0758.1.E2F7, MA0770.1.HSF2, MA0771.1.HSF4, MA0773.1.MEF2D, MA0774.1.MEIS2, MA0776.1.MYBL1, MA0777.1.MYBL2, MA0105.4.NFKB1, MA0780.1.PAX3, MA0783.1.PKNOX2, MA0787.1.POU3F2, MA0788.1.POU3F3, MA0789.1.POU3F4, MA0792.1.POU5F1B, MA0794.1.PROX1, MA0795.1.SMAD3, MA0796.1.TGIF1, MA0797.1.TGIF2, MA0511.2.RUNX2, MA0801.1.MGA, MA0803.1.TBX15, MA0805.1.TBX1, MA0806.1.TBX4, MA0807.1.TBX5, MA0808.1.TEAD3, MA0813.1.TFAP2B, MA0815.1.TFAP2C, MA0816.1.Ascl2, MA0822.1.HES7, MA0823.1.HEY1, MA0826.1.OLIG1, MA0827.1.OLIG3, MA0838.1.CEBPG, MA0845.1.FOXB1, MA0032.2.FOXC1, MA0848.1.FOXO4, MA0849.1.FOXO6, MA0850.1.FOXP3, MA0855.1.RXRB, MA0856.1.RXRG, ...]

[1019 rows x 0 columns]